# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: dronePosVec.proto

from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='dronePosVec.proto',
  package='dronePosVec',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x11\x64ronePosVec.proto\x12\x0b\x64ronePosVec\"\xb5\x01\n\rdronePosition\x12,\n\ndeviceType\x18\x01 \x01(\x0e\x32\x18.dronePosVec.dataDevices\x12\x14\n\x08position\x18\x02 \x03(\x02\x42\x02\x10\x01\x12\x17\n\x0bpositionDot\x18\x03 \x03(\x02\x42\x02\x10\x01\x12\x16\n\nmatrixSize\x18\x04 \x03(\rB\x02\x10\x01\x12\x15\n\trotMatrix\x18\x05 \x03(\x02\x42\x02\x10\x01\x12\x18\n\x0crotMatrixDot\x18\x06 \x03(\x02\x42\x02\x10\x01*<\n\x0b\x64\x61taDevices\x12\x0b\n\x07IMUonly\x10\x00\x12\x0e\n\nCameraOnly\x10\x01\x12\x10\n\x0cKalmanFilter\x10\x02\x62\x06proto3'
)

_DATADEVICES = _descriptor.EnumDescriptor(
  name='dataDevices',
  full_name='dronePosVec.dataDevices',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='IMUonly', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='CameraOnly', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='KalmanFilter', index=2, number=2,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=218,
  serialized_end=278,
)
_sym_db.RegisterEnumDescriptor(_DATADEVICES)

dataDevices = enum_type_wrapper.EnumTypeWrapper(_DATADEVICES)
IMUonly = 0
CameraOnly = 1
KalmanFilter = 2



_DRONEPOSITION = _descriptor.Descriptor(
  name='dronePosition',
  full_name='dronePosVec.dronePosition',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='deviceType', full_name='dronePosVec.dronePosition.deviceType', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='position', full_name='dronePosVec.dronePosition.position', index=1,
      number=2, type=2, cpp_type=6, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=b'\020\001', file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='positionDot', full_name='dronePosVec.dronePosition.positionDot', index=2,
      number=3, type=2, cpp_type=6, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=b'\020\001', file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='matrixSize', full_name='dronePosVec.dronePosition.matrixSize', index=3,
      number=4, type=13, cpp_type=3, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=b'\020\001', file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='rotMatrix', full_name='dronePosVec.dronePosition.rotMatrix', index=4,
      number=5, type=2, cpp_type=6, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=b'\020\001', file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='rotMatrixDot', full_name='dronePosVec.dronePosition.rotMatrixDot', index=5,
      number=6, type=2, cpp_type=6, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=b'\020\001', file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=35,
  serialized_end=216,
)

_DRONEPOSITION.fields_by_name['deviceType'].enum_type = _DATADEVICES
DESCRIPTOR.message_types_by_name['dronePosition'] = _DRONEPOSITION
DESCRIPTOR.enum_types_by_name['dataDevices'] = _DATADEVICES
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

dronePosition = _reflection.GeneratedProtocolMessageType('dronePosition', (_message.Message,), {
  'DESCRIPTOR' : _DRONEPOSITION,
  '__module__' : 'dronePosVec_pb2'
  # @@protoc_insertion_point(class_scope:dronePosVec.dronePosition)
  })
_sym_db.RegisterMessage(dronePosition)


_DRONEPOSITION.fields_by_name['position']._options = None
_DRONEPOSITION.fields_by_name['positionDot']._options = None
_DRONEPOSITION.fields_by_name['matrixSize']._options = None
_DRONEPOSITION.fields_by_name['rotMatrix']._options = None
_DRONEPOSITION.fields_by_name['rotMatrixDot']._options = None
# @@protoc_insertion_point(module_scope)
